name: CD

on:
  push:
    tags:
      - v*.*.*

jobs:
  release-ahk:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile AutoHotKey
        uses: nekocodeX/GitHub-Action-Ahk2Exe@v1.1.0
        with:
          in: win2mac-like-keybinding.ahk
      - uses: softprops/action-gh-release@v1
        with:
          files: win2mac-like-keybinding.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
