name: CI

on:
  push:
    branches:
      - "*"

jobs:
  ahk:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile AutoHotKey
        uses: nekocodeX/GitHub-Action-Ahk2Exe@v1.1.0
        with:
          in: win2mac-like-keybinding.ahk
